### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by smiles724** [lucidrains/equiformer-pytorch#12]
Hi thanks for providing the code. However, I failed to call the Equiformer successfully due to the following error. Can you please help debug the problem? 

![image](https://github.com/lucidrains/equiformer-pytorch/assets/39299863/dd490d71-0e3a-4dff-b6e9-59ed8d475fe8)

**Comment by lucidrains** [comment]
@smiles724 oops, that's a python 3.9 feature

want to try the latest change?

**Comment by smiles724** [comment]
Thanks for your reply. I have deleted the unnecessary line and the code works well.

**Comment by lucidrains** [comment]
@smiles724 oh, it didn't work even with 0.3.10?
