### ISSUE TITLE
Adapting Equiformer for Efficient Handling of Graphs with Sparse Matrix in COO format?

### ISSUE THREAD

**Issue by luwei0917** [lucidrains/equiformer-pytorch#14]
Thank you for implementing Equiformer. Decoupling the model from the original OC20 tasks significantly broadens its applicability.

In my project, I'm utilizing PyTorch Geometric, where batches are merged into a large graph, and edges are represented in COO format of a sparse matrix. I noticed that you have implemented support for sparse matrices. However, the dimension remains NxN, which becomes impractically large with an increased number of nodes.

Could you consider adapting Equiformer to not always operate on an NxN basis, but instead focus on a subset of nodes at a time, with edges defined in COO format?

Thanks.

**Comment by lucidrains** [comment]
has there been any new developments? i feel like we are stuck if diffusion + equivariant networks does not cut it

**Comment by lucidrains** [comment]
a friend just shared this https://t.co/3CJBjyOs38 I really need to get back to open sourcing in this space, even if the audience is an order of magnitude smaller.

**Comment by lucidrains** [comment]
any thoughts on this paper? https://openreview.net/forum?id=Y3BbxvAQS9

**Comment by luwei0917** [comment]
multi-objective optimization is research area worth exploring. but I didn't get much information from a brief scan of this paper. I don't think using Vina score is a good metrics in general.

**Comment by lucidrains** [comment]
@luwei0917 thanks for your thoughts!
