### ISSUE TITLE
Dependency Conflict

### ISSUE THREAD

**Issue by coopersvajda** [lucidrains/equiformer-pytorch#16]
Hey There,
Was attempting to do a pip install and run of equiformer in colab. Ran into a dependency issue. tensorflow-probability 0.22.0 was the native install but it requires a typing extension of 4.6.0 or less. So had to do a tensorflow-probability update prior to the pip install of equiformer. Not a big deal but wanted to post.

**Comment by lucidrains** [comment]
@coopersvajda oh that's strange, i never do tensorflow

why is tensorflow a dep?

**Comment by coopersvajda** [comment]
Using pipdeptree I saw it coming from a package called dopamine. But didn't appear that dopamine was itself stemming off of anything else.

**Comment by coopersvajda** [comment]
Hey I apologize for the confusion. I think I identified why it was throwing errors. I was running it an environment that I appear not to have cleared completely so there was still some hangups from a previous '!pip install torch-geometric'. Started with a truly clean slate and it works great.

**Comment by lucidrains** [comment]
@coopersvajda oh nice! thank you for clearing up the confusion!
