### ISSUE TITLE
Error when use equiformer-pytorch

### ISSUE THREAD

**Issue by WeakerWar** [lucidrains/equiformer-pytorch#4]
Hi, I install the equiformer-pytorch , but there is an error when I use it in my project:

> File "/root/autodl-tmp/project/DeepPROTACs/model.py", line 7, in <module>
>     from equiformer_pytorch import Equiformer
>   File "/root/miniconda3/envs/DeepPROTACs/lib/python3.7/site-packages/equiformer_pytorch/__init__.py", line 1, in <module>
>     from equiformer_pytorch.equiformer_pytorch import Equiformer
>   File "/root/miniconda3/envs/DeepPROTACs/lib/python3.7/site-packages/equiformer_pytorch/equiformer_pytorch.py", line 121, in <module>
>     class Linear(nn.Module):
>   File "/root/miniconda3/envs/DeepPROTACs/lib/python3.7/site-packages/beartype/_decor/main.py", line 193, in beartype
>     return beartype_args_mandatory(obj, conf)
>   File "/root/miniconda3/envs/DeepPROTACs/lib/python3.7/site-packages/beartype/_decor/_core.py", line 123, in beartype_args_mandatory
>     return _beartype_type(cls=obj, conf=conf)  # type: ignore[return-value]
>   File "/root/miniconda3/envs/DeepPROTACs/lib/python3.7/site-packages/beartype/_decor/_core.py", line 313, in _beartype_type
>     f'{repr(cls)} not decoratable by @beartype, as '
> beartype.roar.BeartypeDecorWrappeeException: <class 'equiformer_pytorch.equiformer_pytorch.Linear'> not decoratable by @beartype, as non-dataclasses (i.e., types not decorated by @dataclasses.dataclass) currently unsupported by @beartype.

I thought it was a problem with the version of the beartype package, but when I tried various versions the problem still persisted. I don't know how to fix it?
Thanks!

**Comment by lucidrains** [comment]
@WeakerWar do you have a simple script that replicates this? what version of beartype are you on?

**Comment by lucidrains** [comment]
@WeakerWar let me know if https://github.com/lucidrains/equiformer-pytorch/commit/3faa374963b962f7e0ee46dc351801617f93476b fixes it

what is `DeepPROTACs` ? new paper in the making? :nerd_face:
