### ISSUE TITLE
Why this implementation takes up much more memory than equifold?

### ISSUE THREAD

**Issue by gitabtion** [lucidrains/equiformer-pytorch#5]
Hi, great work! I find this library very memory-intensive. How can I reduce the memory usage? Do you have any plans to reduce the occupation of GPU memory?
When I run the following code, I will get CUDA out of memory Error on RTX4090 which have 24GB gpu memory.
```python
import torch

from equiformer_pytorch.equiformer_pytorch import Equiformer

model = Equiformer(
    dim=128,
    depth=2,
    l2_dist_attention=True,
    reduce_dim_out=True
).to('cuda')

feats = torch.randn(2, 64, 128, device='cuda')
coors = torch.randn(2, 64, 3, device='cuda')
mask = torch.ones(2, 64, dtype=torch.bool, device='cuda')

out = model(feats, coors, mask)
```
and error is 
```
...
File "/xxx/equiformer-pytorch/equiformer_pytorch/equiformer_pytorch.py", line 426, in forward
    out = out + R[..., i] * B[..., i]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.66 GiB (GPU 0; 23.99 GiB total capacity; 21.60 GiB already allocated; 0 bytes free; 22.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
Looking forward to your reply, thanks!

**Comment by gitabtion** [comment]
I try to use this hyper-param to save the memory:
```python
model = Equiformer(
    dim=32,
    depth=6,
    l2_dist_attention=True,
    reduce_dim_out=True,
    dim_head=4,
    heads=4,
    single_headed_kv=True,
    radial_hidden_dim=32,
    num_neighbors=128,
)
```
But it still takes up much more memory than equifold.

**Comment by cyang31** [comment]
Hi, I met with the same issue. My experiments show that the number of neighbors, the input length and the number of degrees influence a lot on GPU usages. I have been keeping track of this issue but see now it is closed. Any successful trick that you would kindly share to reduce the GPU usage? Thanks.
