### ISSUE TITLE
equiformer v2 is out!

### ISSUE THREAD

**Issue by cyang31** [lucidrains/equiformer-pytorch#6]
Would you mind if implementing the equiformer v2? Thanks! https://arxiv.org/abs/2306.12059

**Comment by lucidrains** [comment]
@cyang31 yes i was just looking at this and the improvements look good! i believe the author also have it already open sourced?

regardless, i will be trying to grok [eSCN](https://arxiv.org/abs/2302.03655) and perhaps build out a clean implementation of that paper first

**Comment by yilunliao** [comment]
Yes, the [code](https://github.com/atomicarchitects/equiformer_v2) is open-sourced and complete now.
It is what we use to get the results reported in the paper. 

The checkpoints are available as well.

**Comment by lucidrains** [comment]
@yilunliao congrats on the paper!

**Comment by yilunliao** [comment]
@lucidrains  Thank you : )

**Comment by lucidrains** [comment]
i think i understand now what happened, after reading SCN -> eSCN -> equiformerv2

getting excited about equivariance again 😄

**Comment by lucidrains** [comment]
<img width="509" alt="Screen Shot 2023-07-11 at 11 17 39 AM" src="https://github.com/lucidrains/equiformer-pytorch/assets/108653/56045d53-3d16-403e-9ce6-fb3a7fbce376">

now we need a (much simpler) e2nn library lol

**Comment by lucidrains** [comment]
just a random thought, this should apply to [this approach](https://arxiv.org/abs/2012.10885) as well? https://github.com/lucidrains/lie-transformer-pytorch

**Comment by yilunliao** [comment]
> just a random thought, this should apply to [this approach](https://arxiv.org/abs/2012.10885) as well? https://github.com/lucidrains/lie-transformer-pytorch

I think so. 

At least we can use non-linear attention and non-linear messages for better performance, but I am not familiar with this work.
